# Create a reusable workflow to build deployment app
# https://colinsalmcorner.com/musings-on-reusable-workflows/

############# SECRETS #############
# DEPLOYMENT_PRIVATE_KEY - (optional) deployment private key used to decrypt encrypted deployment

on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the artifact to upload
        type: string
        default: www
  # TODO - may need to also pass secrets here if working with encrypted deployments (to test)
env:
  # TODO - extract from config (would need to be done in separate action that first checks out)
  DEPLOYMENT_NAME: debug_git
  DEPLOYMENT_PRIVATE_KEY: ${{secrets.DEPLOYMENT_PRIVATE_KEY}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          repository: "IDEMSInternational/parenting-app-ui.git"
          # TODO - extract from config
          ref: master
      - uses: actions/checkout@v3
        with:
          lfs: true
          path: ".idems_app/deployments/${{env.DEPLOYMENT_NAME}}"
      - name: Populate Encryption key
        if: env.DEPLOYMENT_PRIVATE_KEY != ''
        run: echo $DEPLOYMENT_PRIVATE_KEY > .idems_app/deployments/$DEPLOYMENT_NAME/encrypted/private.key
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./.yarn/cache
          # If cachebusting required (e.g. breaking yarn changes on update) change `v1` to another number
          key: ${{ runner.os }}-node-modules-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-yarn-v1-
      - name: debug log
        run: |
          echo $(ls .idems_app/deployments)
          echo $(ls .idems_app/deployments/$DEPLOYMENT_NAME)
      - name: Install node modules
        run: yarn install

      # TODO - populate firebase as part of deployment set
      - name: Set deployment
        run: |
          yarn workflow deployment set $DEPLOYMENT_NAME
          echo "export const firebaseConfig = {\"apiKey\":\"\"}" > src/environments/firebaseConfig.ts
      - name: Build
        run: yarn build
        # Tar build folder for faster download and to support format expected by github pages upload artifact action
        # https://github.com/actions/upload-pages-artifact/blob/main/action.yml
      - name: Compress Build Artifact
        run: |
          ls
          chmod -c -R +rX "www/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
          tar \
            --dereference --hard-dereference \
            --directory "www/" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ${{inputs.artifact-name}}
          path: ${{ runner.temp }}/artifact.tar
          if-no-files-found: error
          retention-days: 1
# https://colinsalmcorner.com/musings-on-reusable-workflows/
