##################################################################################
#         Configuration
##################################################################################
env:
  DEPLOYMENT_NAME: "debug_git"
  DEPLOYMENT_PRIVATE_KEY: ${{secrets.DEPLOYMENT_PRIVATE_KEY}}
  FIREBASE_CONFIG: ${{secrets.FIREBASE_CONFIG}}

##################################################################################
#         Main Code
##################################################################################
on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the artifact to upload
        type: string
        default: www
      build-flags:
        description: Additional flags to pass to build command (e.g. base-href)
        type: string
        default: ""
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          repository: "IDEMSInternational/parenting-app-ui.git"
          ref: master
      - uses: actions/checkout@v3
        with:
          lfs: true
          path: ".idems_app/deployments/${{env.DEPLOYMENT_NAME}}"
      - name: Populate Encryption key
        if: env.DEPLOYMENT_PRIVATE_KEY != ''
        run: echo "${{env.DEPLOYMENT_PRIVATE_KEY}}" > ./.idems_app/deployments/${{env.DEPLOYMENT_NAME}}/encrypted/private.key

        # TODO - populate firebase as part of deployment set
      - name: Populate Firebase Config
        if: env.FIREBASE_CONFIG != ''
        run: |
          echo "export const firebaseConfig = ${{env.FIREBASE_CONFIG}}" > src/environments/firebaseConfig.ts
          cat src/environments/firebaseConfig.ts
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./.yarn/cache
          # If cachebusting required (e.g. breaking yarn changes on update) change `v1` to another number
          key: ${{ runner.os }}-node-modules-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-yarn-v1-
      - name: debug log
        run: |
          echo $(ls .idems_app/deployments)
          echo $(ls .idems_app/deployments/$DEPLOYMENT_NAME)
      - name: Install node modules
        run: yarn install

      - name: Set deployment
        run: yarn workflow deployment set $DEPLOYMENT_NAME

      - name: Build
        run: yarn build ${{inputs.build-flags}}
        # Use github pages upload artifact action as also compresses into tar
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: "www/"
          name: ${{inputs.artifact-name}}
      #   # Tar build folder for faster download and to support format expected by github pages upload artifact action
      #   # https://github.com/actions/upload-pages-artifact/blob/main/action.yml
      # - name: Archive Build Artifact
      #   run: |
      #     chmod -c -R +rX "www/" | while read line; do
      #       echo "::warning title=Invalid file permissions automatically fixed::$line"
      #     done
      #     tar \
      #       --dereference --hard-dereference \
      #       --directory "www/" \
      #       -cvf "$RUNNER_TEMP/artifact.tar" \
      #       .
      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v2.2.2
      #   with:
      #     name: ${{inputs.artifact-name}}
      #     path: ${{ runner.temp }}/artifact.tar
      #     if-no-files-found: error
      #     retention-days: 1
# https://colinsalmcorner.com/musings-on-reusable-workflows/

##################################################################################
#         Links
##################################################################################

# Create a reusable workflow to build deployment app
# https://colinsalmcorner.com/musings-on-reusable-workflows/
