# Create a reusable workflow to build deployment app
# https://colinsalmcorner.com/musings-on-reusable-workflows/

############# SECRETS #############
# DEPLOYMENT_PRIVATE_KEY - (optional) deployment private key used to decrypt encrypted deployment

name: App - Build
on:
  workflow_call:
  # TODO - consider any secrets or inputs that should be passed
env:
  # TODO - extract from config (would need to be done in separate action that first checks out)
  DEPLOYMENT_NAME: debug_git
  DEPLOYMENT_PRIVATE_KEY: ${{secrets.DEPLOYMENT_PRIVATE_KEY}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          repository: "IDEMSInternational/parenting-app-ui.git"
          # TODO - extract from config
          ref: master
      - uses: actions/checkout@v3
        with:
          lfs: true
          path: ".idems_app/deployments/${{env.DEPLOYMENT_NAME}}"
      - name: Populate Encryption key
        if: env.DEPLOYMENT_PRIVATE_KEY != ''
        run: echo $DEPLOYMENT_PRIVATE_KEY > .idems_app/deployments/$DEPLOYMENT_NAME/encrypted/private.key
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./.yarn/cache
          # If cachebusting required (e.g. breaking yarn changes on update) change `v1` to another number
          key: ${{ runner.os }}-node-modules-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-yarn-v1-
      - name: debug log
        run: |
          echo $(ls .idems_app/deployments)
          echo $(ls .idems_app/deployments/$DEPLOYMENT_NAME)
      - name: Install node modules
        run: yarn install

      # TODO - populate firebase as part of deployment set
      - name: Set deployment
        run: |
          yarn workflow deployment set $DEPLOYMENT_NAME
          echo "export const firebaseConfig = {\"apiKey\":\"\"}" > src/environments/firebaseConfig.ts
      - name: Build
        run: yarn build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: www
          path: www/**
          if-no-files-found: error
# https://colinsalmcorner.com/musings-on-reusable-workflows/
