# Build and deploy main branch app to github pages
# https://github.com/actions/deploy-pages
# https://github.com/actions/starter-workflows/blob/main/pages/static.yml

# Setup
# Ensure GitHub Pages has been enabled for actions in settings, example url:
# https://github.com/{org}/{repo}/settings/pages

name: Deploy - GH Pages
on:
  push:
    branches:
      - main

env:
  # TODO - should get from repo (used to deploy to github pages nested folder)
  # Not required if using custom domain (TBC)
  BASE_HREF: idems-app-debug-git

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Debug outputs
        run: echo ${{steps.pages.outputs}}
    outputs:
      base-href: ${{steps.pages.outputs.base_path}}

  build_action:
    needs: configure
    uses: ./.github/workflows/app-build.yml
    with:
      artifact-name: github-pages
      # build-flags: "--base-href ${{env.BASE_HREF}}"
      build-flags: --base-href ${{needs.jobs.configure.outputs.base-href}}

  deploy_gh_pages:
    needs: build_action
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      # - name: Setup Pages
      #   uses: actions/configure-pages@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
          preview: false
