# Build and deploy main branch app to github pages
# https://github.com/actions/deploy-pages
# https://github.com/actions/starter-workflows/blob/main/pages/static.yml

# Setup
# Ensure GitHub Pages has been enabled for actions in settings, example url:
# https://github.com/{org}/{repo}/settings/pages

# Known Issues
# Github pages does not support SPA routing, will either need to use app with hashRouter
# or add cloudflare cdn and redirect rules

name: Deploy - GH Pages
on:
  push:
    branches:
      - main

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      # Store base_path as output for use in build job (i.e. git repo name /my-repo )
      base_path: ${{steps.pages.outputs.base_path}}
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Debug outputs
        run: echo '${{ toJSON(steps.pages.outputs) }}'

  build_action:
    needs: configure
    uses: ./.github/workflows/app-build.yml
    with:
      artifact-name: github-pages
      # Pass flag to angular build to deploy site on github pages nested path {org}.github.io/{repo}
      # https://angular.io/guide/deployment#deploy-to-github-pages
      build-flags: --base-href ${{needs.configure.outputs.base_path}}/

  deploy_gh_pages:
    needs: build_action
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
          preview: false
