# Build and deploy app to firebase
# Deploys to "dev" site on "main" branch

##################################################################################
#         Github Secrets (configured per deployment)
##################################################################################
# These should be configured in https://github.com/{org}/{repo}/settings/secrets/actions

# | FIREBASE_PROJECT_ID         | ID of firebase project to use
# | FIREBASE_SERVICE_ACCOUNT    | JSON export of service account (exported from firebase console)

##################################################################################
#         Configuration (updated per deployment)
##################################################################################

env:
  FIREBASE_HOSTING_CHANNEL: dev # | Name of preview channel to deploy to

##################################################################################
#         Main Code
##################################################################################

name: Deploy - Firebase
on:
  push:
    branches:
      - main
      - ci/firebase-dev

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "firebase_dev"
  cancel-in-progress: true

jobs:
  build_action:
    uses: ./.github/workflows/app-build.yml
    with:
      artifact-name: www

  deploy_dev:
    needs: build_action
    runs-on: ubuntu-latest
    outputs:
      urls: ${{ steps.deploy.outputs.urls }}
    steps:
      - uses: actions/checkout@v3
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: www

      - name: Extract Build folder
        run: |
          mkdir www
          tar -xf artifact.tar --directory www

      - name: Populate Firebase JSON
        run: |
          FIREBASE_JSON='{"public": "www", "ignore": ["firebase.json"], "rewrites": [{"source": "**","destination": "/index.html" } ]}'
          echo $FIREBASE_JSON > firebase.json
          cat firebase.json
      - id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "${{ secrets.GITHUB_TOKEN }}"
          channelId: "${{ secrets.FIREBASE_HOSTING_CHANNEL }}"
          expires: "30d"
#  firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
