# Create a PR for new content branches

# SETUP
# See https://github.com/marketplace/actions/create-pull-request#workflow-permissions

name: PR - Create
on:
  push:
    branches:
      - content/*
jobs:
  pr_create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          ref: "${{github.event.inputs.build_branch}}"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          title: ${{github.ref_name}}
          base: main
          delete-branch: true
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
