# Create a PR for new content branches
# https://cli.github.com/manual/gh_pr_create

# SETUP
# See https://github.com/marketplace/actions/create-pull-request#workflow-permissions

name: PR - Create
on:
  push:
    branches:
      - content/*
jobs:
  pr_create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh pr create --base main --head ${{github.ref_name}} --title 'Merge ${{github.ref_name}}' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
