# Create a PR for new content branches
# https://cli.github.com/manual/gh_pr_create

############# SECRETS #############
# DEPLOYMENT_PRIVATE_KEY - deployment private key used to decrypt deployment

name: PR - Preview
on:
  push:
    branches:
      - content/*
env:
  # TODO - extract from config
  DEPLOYMENT_NAME: debug_git
  DEPLOYMENT_PRIVATE_KEY: ${{secrets.DEPLOYMENT_PRIVATE_KEY}}
jobs:
  deployment_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          repository: "IDEMSInternational/parenting-app-ui.git"
          # TODO - extract from config
          ref: master
      - uses: actions/checkout@v3
        with:
          lfs: true
          path: ".idems_app/deployments/$DEPLOYMENT_NAME"
      - name: Populate Encryption key
        if: $DEPLOYMENT_PRIVATE_KEY
        run: echo $DEPLOYMENT_PRIVATE_KEY > .idems_app/deployments/$DEPLOYMENT_NAME/encrypted/private.key
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./.yarn/cache
          # If cachebusting required (e.g. breaking yarn changes on update) change `v1` to another number
          key: ${{ runner.os }}-node-modules-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-yarn-v1-
      - run: yarn install
      - run: |
          echo $(ls)
          echo $(ls .idems_app)
          echo $(ls .idems_app/deployments)
          echo $(ls .idems_app/deployments/$DEPLOYMENT_NAME)
      # TODO - populate firebase as part of deployment set
      # - name: set deployment
      #   run: |
      #     yarn workflow deployment set $DEPLOYMENT_NAME
      #     echo "export const firebaseConfig = {}" > src/environments/firebaseConfig.ts
      # - name: build
      #   run: yarn build
