# Create a PR for new content branches
# https://cli.github.com/manual/gh_pr_create

############# SECRETS #############
# DEPLOYMENT_PRIVATE_KEY - (optional) deployment private key used to decrypt encrypted deployment

name: PR - Preview
on:
  push:
    branches:
      - content/*
jobs:
  build_action:
    uses: ./.github/workflows/app-build.yml
    with:
      artifact-name: pr-preview
  deploy_preview:
    needs: build_action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: pr-preview
      - name: debug logs
        run: ls
      - name: Extract Build folder
        run: |
          mkdir www
          tar -xf artifact.tar --directory www
      # TODO - configure firebase as part of deployment and deploy www folder
      # NOTE - could be worth waiting for github pages preview support (https://github.com/actions/deploy-pages)
      # https://github.com/actions/deploy-pages/pull/61
      - name: deploy
        run: |
          ls
          echo "--------------"
          ls www
